apiVersion: apps/v1
kind: Deployment
metadata:
  name: singlezonepool-zrs-shared
spec:
  selector:
    matchLabels:
      app: singlezonepool-zrs-shared
  template:
    metadata:
      labels:
        app: singlezonepool-zrs-shared
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["/bin/bash"]
        args: ["-c", "while true; do date | tee -a /data/myfile.txt; sleep 15; done"]
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: singlezonepool-zrs-shared
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: multizone
                operator: In
                values:
                - "false"   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: singlezonepool-zrs-shared
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azuredisk-premium-ssd-zrs-replicas
  resources:
    requests:
      storage: 30Gi
