apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zrs-shared-class
parameters:
  cachingmode: None
  skuName: StandardSSD_ZRS
  maxShares: "2"
provisioner: disk2.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true